Section extra_specs.
Context `{RRGS : !refinedrustGS Σ}.

Section resolve_ghost.
  Context {T_rt : RT}.
  Context (T_ty : type (T_rt)).

  (* NOTE Resolution of ghost variables over the invariant -- not currently automatically generated by the frontend. *)
  Lemma resolve_ghost_Vec_T π E L rm l rs T :
    (∀ li, resolve_ghost_iter π E L rm false li (ty_syn_type T_ty) (replicate (length rs) (◁ T_ty))%I (Owned false) rs [] 0%nat (λ L2 rs' R progress,
      T L2 (#rs') R progress)) ⊢
    resolve_ghost π E L rm true l (◁ (Vec_inv_t T_rt <TY> T_ty <INST!>)) (Owned false) (#rs) T.
  Proof.
  Admitted.
  Definition resolve_ghost_Vec_T_inst := [instance resolve_ghost_Vec_T].
  Global Existing Instance resolve_ghost_Vec_T_inst.
End resolve_ghost.

Section Vec_inv_t_ne.
  Context `{!refinedrustGS Σ}.

  Global Instance RawVec_inv_t_contr {rt1 T_rt : RT} (T : type rt1 → type T_rt) :
    TypeNonExpansive T →
    TypeContractive (λ ty, RawVec_inv_t T_rt <TY> (T ty) <INST!>).
  Proof.
    intros.
    apply ex_inv_def_contractive.
    - constructor.
      + simpl. apply direct_lft_morph_make_const.
      + solve_type_proper.
      + solve_type_proper.
    - (* TODO improve *) 
      unfold RawVec_ty.
      simpl.
      unfold RawVec_sls.
      apply _.
  Qed.
  Global Instance RawVec_inv_t_ne {rt1 T_rt : RT} (T : type rt1 → type T_rt) :
    TypeNonExpansive T →
    TypeNonExpansive (λ ty, RawVec_inv_t T_rt <TY> (T ty) <INST!>).
  Proof. apply _. Qed.
End Vec_inv_t_ne. 

Section Vec_inv_t_ne.
  Context `{!refinedrustGS Σ}.

  Global Instance Vec_inv_t_contr {rt1 T_rt : RT} (T : type rt1 → type T_rt) :
    TypeNonExpansive T →
    TypeContractive (λ ty, Vec_inv_t T_rt <TY> (T ty) <INST!>).
  Proof.
    intros X.
    apply ex_inv_def_contractive.
    - constructor.
      + simpl. apply ty_lft_morphism_to_direct.
        apply X.
      + solve_proper_prepare.
        repeat solve_proper_step.
        rewrite type_dist2_st. done.
      + solve_proper_prepare.
        repeat solve_proper_step.
        erewrite type_ne_syn_type; last apply type_dist_later2_st.
        done.
    - (* TODO improve *)
      unfold Vec_ty.
      unfold Vec_sls. 
      unfold RawVec_st.
      unfold RawVec_sls.
      apply _.
  Qed.
  Global Instance Vec_inv_t_ne {rt1 T_rt : RT} (T : type rt1 → type T_rt) :
    TypeNonExpansive T →
    TypeNonExpansive (λ ty, Vec_inv_t T_rt <TY> (T ty) <INST!>).
  Proof. apply _. Qed.
End Vec_inv_t_ne. 

End extra_specs.
